services:
  - type: web
    name: adobe-upload-api
    env: python
    plan: free
    region: oregon
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    autoDeploy: true
